### ISSUE TITLE
Inventory list cards 

### ISSUE THREAD

**Issue by ATHARVA47** [MadhurDixit13/86_No_More_FrontEnd#3]
**Describe the bug**
The cards on the inventory list page are not spaced out and are overlapping

**To Reproduce**
1. Go to inventory list page (Third button in the navigation bar at the top)
3. See error

**Expected behavior**
The cards should be evenly spaced, there should be space between the cards at the top and bottom.

**Screenshots of the issue**
![image](https://github.com/MadhurDixit13/86_No_More_FrontEnd/assets/75237232/f61799d1-aad1-43de-be01-920abcfcedad)

**Comment by Tanvi0701** [comment]
Issue has been resolved.
